from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from rl_x.algorithms.reppo_dime.flax_full_jit.reppo_dime import RePPO_DIME
from rl_x.algorithms.reppo_dime.flax_full_jit.default_config import get_config
from rl_x.algorithms.reppo_dime.flax_full_jit.general_properties import GeneralProperties


REPPO_DIME_FLAX_FULL_JIT = extract_algorithm_name_from_file(__file__)
register_algorithm(REPPO_DIME_FLAX_FULL_JIT, get_config, RePPO_DIME, GeneralProperties)
