# Denoising Diffusion Model
name: ddm
integrator: EM
# diff_steps: 16
diff_steps: 8
diff_coef: 1.0

init_std: 1.0
learn_diff_coef: True

defaults:
  - control_net: cond_control_net
  - diff_coef_schedule: cosine
