from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.gym.classic.multi_goal.create_env import create_train_and_eval_env
from rl_x.environments.gym.classic.multi_goal.default_config import get_config
from rl_x.environments.gym.classic.multi_goal.general_properties import GeneralProperties


GYM_CLASSIC_MULTI_GOAL = extract_environment_name_from_file(__file__)
register_environment(GYM_CLASSIC_MULTI_GOAL, get_config, create_train_and_eval_env, GeneralProperties)
