from ml_collections import config_dict


def get_config(environment_name):
    config = {
        "name": environment_name,
        "nr_envs": 4096,
        "seed": 1,
        "render": False,
        "device": "gpu",
        "copy_train_env_for_eval": True,
        "train_robot": "booster_t1",
        "control_type": "pd",
        "simulator": {
            "model_source": "rcssservermj",
            "rcssservermj_root": "",
            "world_source": "rlx",
        },
        "training_stage": "stage_1",
        "command": {
            "type": "random_ball_velocity",
            "sampling_type": "step_probability",
            "max_ball_velocity": 1.0,
            "resampling_time_s": 4.0,
            "zero_clip_threshold_percentage": 0.1,
            "all_zero_chance": 0.04,
            "single_zero_chance": 0.005,
        },
        "ball": {
            "spawn_radius": 10.0,
        },
        "stages": {
            "stage_1": {
                "ball_spawn_radius": 10.0,
                "ball_spawn_radius_min": 10.0,
                "curriculum_ball_spawn_radius": False,
                "spawn_in_vision": True,
                "spawn_half_angle_degrees": 45.0,
                "sensing_half_horizontal_range": 87.0,
                "sensing_half_vertical_range": 58.0,
                "env_curriculum_initial_coeff": 1.0,
                "update_env_curriculum": False,
                "reward": {
                    "base_orientation_coeff": 1.0,
                    "feet_orientation_coeff": 1.0,
                    "feet_distance_coeff": 1.0,
                    "feet_clearance_coeff": 2.0,
                    "termination_coeff": -10.0,
                    "reference_joint_position_coeff": 1.2,
                    "symmetric_action_coeff": -0.001,
                    "joint_torque_coeff": -0.003,
                    "joint_speed_coeff": -0.0001,
                    "action_smoothness_coeff": -0.01,
                    "collision_coeff": 2.0,
                    "active_sensing_coeff": 0.2,
                    "chasing_coeff": 2.0,
                    "progress_to_ball_coeff": 20.0,
                    "progress_to_ball_clip": 0.05,
                    "projected_ball_velocity_coeff": 0.0,
                    "yaw_alignment_coeff": 0.2,
                    "yaw_alignment_no_ball_coeff": -0.2,
                },
            },
            "stage_2": {
                "ball_spawn_radius": 2.0,
                "ball_spawn_radius_min": 2.0,
                "curriculum_ball_spawn_radius": False,
                "spawn_in_vision": True,
                "spawn_half_angle_degrees": 40.0,
                "sensing_half_horizontal_range": 43.5,
                "sensing_half_vertical_range": 29.0,
                "env_curriculum_initial_coeff": 1.0,
                "update_env_curriculum": False,
                "reward": {
                    "base_orientation_coeff": 1.0,
                    "feet_orientation_coeff": 1.0,
                    "feet_distance_coeff": 1.0,
                    "feet_clearance_coeff": 2.0,
                    "termination_coeff": -10.0,
                    "reference_joint_position_coeff": 0.0,
                    "symmetric_action_coeff": -0.001,
                    "joint_torque_coeff": -0.015,
                    "joint_speed_coeff": -0.0001,
                    "action_smoothness_coeff": -0.01,
                    "collision_coeff": 2.0,
                    "active_sensing_coeff": 0.2,
                    "chasing_coeff": 1.0,
                    "progress_to_ball_coeff": 0.0,
                    "progress_to_ball_clip": 0.05,
                    "projected_ball_velocity_coeff": 1.5,
                    "yaw_alignment_coeff": 0.2,
                    "yaw_alignment_no_ball_coeff": -0.2,
                },
            },
        },
        "sensing": {
            "camera_site_name": "camera",
            "ball_site_name": "B-vismarker",
            "half_horizontal_range": 43.5,
            "half_vertical_range": 29.0,
            "max_ball_unseen_seconds": 0.3,
        },
        "gait_manager": {
            "type": "default",
            "gait_period": 0.64,
            "gait_period_randomization_width": 0.0,
            "randomize_phase": False,
        },
        "env_curriculum_nr_levels": 100,
        "env_curriculum_level_success_episode_return": 10.0,
        "domain_randomization": {
            "sampling_type": "step_probability_and_reset",
            "action_delay": {
                "type": "default",
                "max_nr_delay_steps": 1,
                "mixed_chance": 0.05,
            },
            "initial_state": {
                "type": "random",
                "roll_angle_pi_factor": 0.05,
                "pitch_angle_pi_factor": 0.05,
                "yaw_angle_pi_factor": 1.0,
                "actuator_joint_position_offset_to_nominal": 0.02,
                "actuator_joint_nominal_position_factor": 0.5,
                "joint_velocity_max_factor": 0.1,
                "trunk_velocity_clip_mass_factor": 0.1,
                "trunk_velocity_clip_limit": 0.5,
            },
            "joint_dropout": {
                "type": "default",
                "dropout_open_chance": 0.0,
                "dropout_lock_chance": 0.0,
            },
            "mujoco_model": {
                "type": "default",
                "friction_tangential_factor": 0.5,
                "friction_torsional_factor": 0.5,
                "friction_rolling_factor": 0.5,
                "stiffness_factor": 0.0,
                "damping_factor": 0.0,
                "foot_solimp_factor": 0.0,
                "add_impratio": 0.0,
                "xy_gravity": 0.0,
                "z_gravity_factor": 0.0,
                "density_factor": 0.0,
                "viscosity_factor": 0.0,
            },
            "observation_noise": {
                "type": "default",
                "joint_position": 0.01,
                "joint_velocity": 0.5,
                "imu_angular_velocity": 0.1,
                "gravity_vector": 0.02,
                "exteroception": 0.01,
                "ball_position": 0.05,
            },
            "perturbation": {
                "sampling_type": "step_probability",
                "type": "default",
                "trunk_velocity_clip_mass_factor": 0.1,
                "trunk_velocity_clip_limit": 1.0,
                "trunk_velocity_add_chance": 0.5,
                "max_joint_velocity": 0.1,
                "max_joint_position": 0.01,
            },
            "seen_robot": {
                "type": "default",
                "robot_size_scaling_factor": 0.0,
                "coupled_mass_inertia_factor": 0.0,
                "decoupled_mass_inertia_factor": 0.0,
                "add_base_mass": 2.0,
                "add_com_displacement": 0.04,
                "add_inertia_orientation_rad": 0.0,
                "add_body_position": 0.0,
                "add_body_orientation_rad": 0.0,
                "add_imu_position": 0.0,
                "foot_size_factor": 0.0,
                "joint_axis_angle_rad": 0.0,
                "torque_limit_factor": 0.05,
                "torque_limit_min_factor": -0.05,
                "torque_limit_max_factor": 0.0,
                "add_actuator_joint_nominal_position": 0.02,
                "joint_velocity_max_factor": 0.0,
                "add_joint_range": 0.0,
                "joint_damping_factor": 0.0,
                "add_joint_damping": 0.0,
                "joint_armature_factor": 0.0,
                "add_joint_armature": 0.0,
                "joint_stiffness_factor": 0.0,
                "add_joint_stiffness": 0.0,
                "joint_friction_loss_factor": 0.0,
                "add_joint_friction_loss": 0.0,
                "p_gain_factor": 0.3,
                "d_gain_factor": 0.2,
                "scaling_factor_factor": 0.05,
            },
            "unseen_robot": {
                "type": "default",
                "mass_inertia_factor": 0.0,
                "com_factor": 0.0,
                "body_position_factor": 0.0,
                "joint_damping_factor": 0.0,
                "joint_armature_factor": 0.0,
                "joint_stiffness_factor": 0.0,
                "joint_friction_loss_factor": 0.0,
                "p_gain_factor": 0.0,
                "d_gain_factor": 0.0,
                "position_offset": 0.0,
            },
        },
        "policy_exteroceptive_observation_type": "none",
        "critic_exteroceptive_observation_type": "none",
        "reward": {
            "type": "default",
            "base_orientation_coeff": 1.0,
            "feet_orientation_coeff": 1.0,
            "feet_distance_coeff": 1.0,
            "feet_clearance_coeff": 2.0,
            "termination_coeff": -10.0,
            "reference_joint_position_coeff": 1.2,
            "symmetric_action_coeff": -0.001,
            "joint_torque_coeff": -0.015,
            "joint_speed_coeff": -0.0001,
            "action_smoothness_coeff": -0.01,
            "collision_coeff": 2.0,
            "active_sensing_coeff": 0.2,
            "chasing_coeff": 2.0,
            "progress_to_ball_coeff": 2.0,
            "progress_to_ball_clip": 0.05,
            "projected_ball_velocity_coeff": 0.0,
            "ball_velocity_tracking_temperature": 1.0,
            "yaw_alignment_coeff": 0.2,
            "yaw_alignment_no_ball_coeff": -0.2,
            "yaw_alignment_no_ball_max_yaw_rate": 2.0,
            "reference_joint_target_scale": 0.17,
            "reference_joint_double_support_threshold": 0.1,
            "feet_phase_swing_height": 0.12,
            "feet_phase_tracking_sigma": 0.1,
            "feet_height_on_flat_ground": 0.01,
        },
        "termination": {
            "type": "below_height",
            "height_percentage_threshold": 0.6,
        },
        "terrain": {
            "type": "plane",
            "wave_fn_min": 0,
            "wave_fn_max": 2,
            "wave_height_max_per_m_factor": 0.3,
            "random_height_max_per_m_factor": 0.04,
            "block_probability": 0.5,
            "block_length_in_meters": 0.5,
            "block_height_max_per_m_factor": 0.1,
        },
        "add_goal_arrow": False,
        "timestep": 0.005,
        "episode_length_in_seconds": 20,
    }

    return config_dict.ConfigDict(config)
