from ml_collections import config_dict


def get_config(environment_name):
    config = {
        "name": environment_name,
        "nr_envs": 4096,
        "seed": 1,
        "render": False,
        "device": "gpu",
        "copy_train_env_for_eval": True,
        "train_robot": "booster_t1",
        "control_type": "pd",
        "training_stage": "stage_1",
        "teacher_policy": {
            "enabled": True,
            "base_policy_checkpoint": "rl_x/environments/custom_mujoco/robocup_soccer/latest.model",
            "controller": "dribble_walk",
            # Defaults copied from fcp origin/dribble-walk.
            "pi_kp": 1.490765701739443,
            "pi_ki": 0.20807633019423477,
            "integral_clip": 0.18284350087572418,
            "integral_decay": 0.7174236267952669,
            "arrival_radius": 0.4861103023959695,
            "command_x_clip": 1.9455552264587892,
            "command_y_clip": 0.7342257791292639,
            "command_yaw_clip": 1.209483865054054,
            "angular_command_gain": 0.4,
            "max_command_velocity": 0.9344823878175175,
            "dribble_ball_standoff": 1.0,
            "dribble_line_tolerance": 0.5,
            "dribble_ball_push_through": 0.3,
            "dribble_goal_x": 28.5,
            "dribble_goal_y": 0.0,
            "dribble_use_dynamic_direction": True,
            "dribble_goal_lookahead": 20.0,
            "nominal_command_ball_velocity_gain": 0.25,
            "nominal_command_position_gain_x": 0.6,
            "nominal_command_position_gain_y": 0.9,
            "nominal_command_yaw_gain": 0.7,
            "nominal_command_target_ball_x": 0.2,
            "nominal_command_target_ball_y": 0.0,
            "nominal_command_max_x": 0.3,
            "nominal_command_max_y": 0.2,
            "nominal_command_max_yaw": 0.5,
            "nominal_command_contact_distance": 1.2,
            "nominal_command_contact_blend_width": 0.6,
            "nominal_command_contact_drive_speed": 0.2,
            "nominal_command_min_toward_ball_speed": 0.12,
            "nominal_command_noise_std": [0.0, 0.0, 0.0],
        },
        "teacher_imitation_schedule": {
            "enabled": True,
            "start_weight": 0.5,
            "end_weight": 0.0,
            "anneal_timesteps": 2000000,
            "success_distance": 1.0,
        },
        "penalty_schedule": {
            "enabled": True,
            "start_coeff": 0.0,
            "end_coeff": 1.0,
            "anneal_timesteps": 50000000,
        },
        "dribble_curriculum": {
            "enabled": True,
            "nr_levels": 100,
            "near_horizon_fraction": 0.95,
            # Level 0: teacher cloning only. Later levels turn on the FCP dribble
            # reward and tighten possession. Teacher regularization reaches zero
            # only in the final level.
            "teacher_imitation_weights": [1.0, 0.75, 0.5, 0.25, 0.0],
            "fcp_dribble_coeffs": [0.0, 1.0, 1.0, 1.0, 1.0],
            "possession_enabled": [False, True, True, True, True],
            "possession_min_x": [-0.25, -0.15, -0.10, -0.08, -0.08],
            "possession_max_x": [0.75, 0.45, 0.35, 0.26, 0.26],
            "possession_max_abs_y": [0.45, 0.25, 0.18, 0.12, 0.12],
            "immediate_max_x": [1.20, 0.65, 0.50, 0.40, 0.40],
            "immediate_max_abs_y": [0.75, 0.35, 0.28, 0.20, 0.20],
        },
        "stages": {
            "stage_1": {
                "teacher_policy": {
                    "enabled": True,
                },
                "teacher_imitation_schedule": {
                    "enabled": True,
                    "start_weight": 1.0,
                    "end_weight": 1.0,
                    "anneal_timesteps": 1,
                    "success_distance": 0.35,
                },
                "penalty_schedule": {
                    "enabled": False,
                    "start_coeff": 1.0,
                    "end_coeff": 1.0,
                    "anneal_timesteps": 1,
                },
                "target": {
                    "train_initial_orientation_min": -180.0,
                    "train_initial_orientation_max": 180.0,
                    "eval_initial_orientation": 0.0,
                    "orientation_change_mode": "ball_displacement",
                    "orientation_change_ball_displacement": 0.5,
                    "orientation_change_probability": 1 / 200,
                    "max_rotation_diff": 10.0,
                },
                "ball": {
                    "spawn_radius": 0.23,
                    "spawn_half_angle_degrees": 10.0,
                    "spawn_in_vision": True,
                    "spawn_rel_x_range": [0.21, 0.25],
                    "spawn_rel_y_range": [-0.025, 0.025],
                    "observation_distance_scale": 1.0,
                    "position_resampling_enabled": False,
                    "position_resampling_probability": 0.0,
                    "position_resampling_min_steps": 50,
                    "position_resampling_in_eval": False,
                },
                "ball_command": {
                    "max_velocity": 1.0,
                    "resampling_time_s": 4.0,
                    "resample_within_episode": True,
                    "zero_clip_threshold": 0.1,
                    "all_zero_chance": 0.0,
                },
                "reward": {
                    "ball_velocity_tracking_coeff": 0.0,
                    "chasing_ball_coeff": 64.0,
                    "chasing_ball_temperature": 2.0,
                    "com_chasing_ball_coeff": 0.0,
                    "close_ball_band_coeff": 0.0,
                    "yaw_to_ball_coeff": 0.0,
                    "yaw_alignment_coeff": 0.0,
                    "fcp_dribble_coeff": 1.0,
                    "fcp_dribble_lateral_coeff": 0.5,
                    "fcp_dribble_forward_clip": 0.8,
                    "fcp_dribble_gate_by_possession": False,
                    "ball_possession_coeff": 0.0,
                    "foot_air_time_coeff": 0.0,
                    "symmetry_air_coeff": 0.0,
                    "foot_slip_coeff": 0.0,
                    "foot_z_velocity_coeff": 0.0,
                    "feet_flat_coeff": 0.0,
                    "feet_phase_coeff": 0.0,
                    "feet_yaw_coeff": 0.0,
                    "feet_lateral_distance_coeff": 0.0,
                },
                "termination": {
                    "enable_possession_termination": False,
                    "possession_warmup_steps": 50,
                    "possession_min_x": -0.25,
                    "possession_max_x": 0.75,
                    "possession_max_abs_y": 0.45,
                    "immediate_max_x": 1.20,
                    "immediate_max_abs_y": 0.75,
                    "enable_ball_stagnation_termination": False,
                },
            },
            "stage_2": {
                "teacher_policy": {
                    "enabled": True,
                },
                "teacher_imitation_schedule": {
                    "enabled": True,
                    "start_weight": 0.5,
                    "end_weight": 0.5,
                    "anneal_timesteps": 1,
                    "success_distance": 0.35,
                },
                "penalty_schedule": {
                    "enabled": False,
                    "start_coeff": 1.0,
                    "end_coeff": 1.0,
                    "anneal_timesteps": 1,
                },
                "target": {
                    "train_initial_orientation_min": -180.0,
                    "train_initial_orientation_max": 180.0,
                    "eval_initial_orientation": 0.0,
                    "orientation_change_probability": 1 / 200,
                    "max_rotation_diff": 10.0,
                },
                "ball": {
                    "spawn_radius": 0.23,
                    "spawn_half_angle_degrees": 10.0,
                    "spawn_in_vision": True,
                    "spawn_rel_x_range": [0.21, 0.25],
                    "spawn_rel_y_range": [-0.025, 0.025],
                    "observation_distance_scale": 1.0,
                    "position_resampling_enabled": False,
                    "position_resampling_probability": 0.0,
                    "position_resampling_min_steps": 50,
                    "position_resampling_in_eval": False,
                },
                "ball_command": {
                    "max_velocity": 1.0,
                    "resampling_time_s": 4.0,
                    "resample_within_episode": True,
                    "zero_clip_threshold": 0.1,
                    "all_zero_chance": 0.0,
                },
                "reward": {
                    "ball_velocity_tracking_coeff": 0.0,
                    "chasing_ball_coeff": 0.0,
                    "com_chasing_ball_coeff": 0.0,
                    "close_ball_band_coeff": 0.0,
                    "yaw_to_ball_coeff": 0.0,
                    "yaw_alignment_coeff": 0.0,
                    "fcp_dribble_coeff": 1.0,
                    "fcp_dribble_lateral_coeff": 0.5,
                    "fcp_dribble_forward_clip": 0.8,
                    "fcp_dribble_gate_by_possession": True,
                    "ball_possession_coeff": 0.0,
                    "foot_air_time_coeff": 0.0,
                    "symmetry_air_coeff": 0.0,
                    "foot_slip_coeff": 0.0,
                    "foot_z_velocity_coeff": 0.0,
                    "feet_flat_coeff": 0.0,
                    "feet_phase_coeff": 0.0,
                    "feet_yaw_coeff": 0.0,
                    "feet_lateral_distance_coeff": 0.0,
                },
                "termination": {
                    "enable_possession_termination": True,
                    "possession_warmup_steps": 50,
                    "possession_min_x": -0.15,
                    "possession_max_x": 0.45,
                    "possession_max_abs_y": 0.25,
                    "immediate_max_x": 0.65,
                    "immediate_max_abs_y": 0.35,
                    "enable_ball_stagnation_termination": False,
                },
            },
            "stage_3": {
                "teacher_policy": {
                    "enabled": True,
                },
                "teacher_imitation_schedule": {
                    "enabled": True,
                    "start_weight": 0.5,
                    "end_weight": 0.5,
                    "anneal_timesteps": 1,
                    "success_distance": 0.35,
                },
                "penalty_schedule": {
                    "enabled": False,
                    "start_coeff": 1.0,
                    "end_coeff": 1.0,
                    "anneal_timesteps": 1,
                },
                "target": {
                    "train_initial_orientation_min": -180.0,
                    "train_initial_orientation_max": 180.0,
                    "eval_initial_orientation": 0.0,
                    "orientation_change_probability": 1 / 200,
                    "max_rotation_diff": 10.0,
                },
                "ball": {
                    "spawn_radius": 0.23,
                    "spawn_half_angle_degrees": 10.0,
                    "spawn_in_vision": True,
                    "spawn_rel_x_range": [0.21, 0.25],
                    "spawn_rel_y_range": [-0.025, 0.025],
                    "observation_distance_scale": 1.0,
                    "position_resampling_enabled": False,
                    "position_resampling_probability": 0.0,
                    "position_resampling_min_steps": 50,
                    "position_resampling_in_eval": False,
                },
                "ball_command": {
                    "max_velocity": 1.0,
                    "resampling_time_s": 4.0,
                    "resample_within_episode": True,
                    "zero_clip_threshold": 0.1,
                    "all_zero_chance": 0.0,
                },
                "reward": {
                    "ball_velocity_tracking_coeff": 0.0,
                    "chasing_ball_coeff": 0.0,
                    "com_chasing_ball_coeff": 0.0,
                    "close_ball_band_coeff": 0.0,
                    "yaw_to_ball_coeff": 0.0,
                    "yaw_alignment_coeff": 0.0,
                    "fcp_dribble_coeff": 1.0,
                    "fcp_dribble_lateral_coeff": 0.5,
                    "fcp_dribble_forward_clip": 0.8,
                    "fcp_dribble_gate_by_possession": True,
                    "ball_possession_coeff": 0.0,
                    "foot_air_time_coeff": 0.0,
                    "symmetry_air_coeff": 0.0,
                    "foot_slip_coeff": 0.0,
                    "foot_z_velocity_coeff": 0.0,
                    "feet_flat_coeff": 0.0,
                    "feet_phase_coeff": 0.0,
                    "feet_yaw_coeff": 0.0,
                    "feet_lateral_distance_coeff": 0.0,
                },
                "termination": {
                    "enable_possession_termination": True,
                    "possession_warmup_steps": 50,
                    "possession_min_x": -0.10,
                    "possession_max_x": 0.35,
                    "possession_max_abs_y": 0.18,
                    "immediate_max_x": 0.50,
                    "immediate_max_abs_y": 0.28,
                    "enable_ball_stagnation_termination": False,
                },
            },
            "stage_4": {
                "teacher_policy": {
                    "enabled": True,
                },
                "teacher_imitation_schedule": {
                    "enabled": True,
                    "start_weight": 0.5,
                    "end_weight": 0.5,
                    "anneal_timesteps": 1,
                    "success_distance": 0.35,
                },
                "penalty_schedule": {
                    "enabled": False,
                    "start_coeff": 1.0,
                    "end_coeff": 1.0,
                    "anneal_timesteps": 1,
                },
                "target": {
                    "train_initial_orientation_min": -180.0,
                    "train_initial_orientation_max": 180.0,
                    "eval_initial_orientation": 0.0,
                    "orientation_change_probability": 1 / 200,
                    "max_rotation_diff": 10.0,
                },
                "ball": {
                    "spawn_radius": 0.23,
                    "spawn_half_angle_degrees": 10.0,
                    "spawn_in_vision": True,
                    "spawn_rel_x_range": [0.21, 0.25],
                    "spawn_rel_y_range": [-0.025, 0.025],
                    "observation_distance_scale": 1.0,
                    "position_resampling_enabled": False,
                    "position_resampling_probability": 0.0,
                    "position_resampling_min_steps": 50,
                    "position_resampling_in_eval": False,
                },
                "ball_command": {
                    "max_velocity": 1.0,
                    "resampling_time_s": 4.0,
                    "resample_within_episode": True,
                    "zero_clip_threshold": 0.1,
                    "all_zero_chance": 0.0,
                },
                "reward": {
                    "ball_velocity_tracking_coeff": 0.0,
                    "chasing_ball_coeff": 0.0,
                    "com_chasing_ball_coeff": 0.0,
                    "close_ball_band_coeff": 0.0,
                    "yaw_to_ball_coeff": 0.0,
                    "yaw_alignment_coeff": 0.0,
                    "fcp_dribble_coeff": 1.0,
                    "fcp_dribble_lateral_coeff": 0.5,
                    "fcp_dribble_forward_clip": 0.8,
                    "fcp_dribble_gate_by_possession": True,
                    "ball_possession_coeff": 0.0,
                    "foot_air_time_coeff": 0.0,
                    "symmetry_air_coeff": 0.0,
                    "foot_slip_coeff": 0.0,
                    "foot_z_velocity_coeff": 0.0,
                    "feet_flat_coeff": 0.0,
                    "feet_phase_coeff": 0.0,
                    "feet_yaw_coeff": 0.0,
                    "feet_lateral_distance_coeff": 0.0,
                },
                "termination": {
                    "enable_possession_termination": True,
                    "possession_warmup_steps": 50,
                    "possession_min_x": -0.08,
                    "possession_max_x": 0.26,
                    "possession_max_abs_y": 0.12,
                    "immediate_max_x": 0.40,
                    "immediate_max_abs_y": 0.20,
                    "enable_ball_stagnation_termination": False,
                },
            },
        },
        "ball": {
            "spawn_radius": 5.0,
            "spawn_half_angle_degrees": 10.0,
            "spawn_in_vision": True,
            "spawn_rel_x_range": [4.5, 5.5],
            "spawn_rel_y_range": [-1.5, 1.5],
            "observation_distance_scale": 6.0,
            "observation_frame_offset": [0.0, 0.0, 0.24],
            "observation_distance_xy_only": True,
            "velocity_observation_scale": 10.0,
            "position_resampling_enabled": False,
            "position_resampling_probability": 0.0,
            "position_resampling_min_steps": 50,
            "position_resampling_in_eval": False,
        },
        "sensing": {
            "camera_site_name": "camera",
            "ball_site_name": "B-vismarker",
            "half_horizontal_range": 60.0,
            "half_vertical_range": 60.0,
            "max_ball_unseen_seconds": 0.06,
            "initial_unseen_grace_seconds": 1.0,
        },
        "ball_command": {
            "max_velocity": 1.0,
            "resampling_time_s": 4.0,
            "resample_within_episode": True,
            "zero_clip_threshold": 0.1,
            "all_zero_chance": 0.04,
        },
        "target": {
            "max_rotation_diff": 20.0,
            "max_rotation_dist": 80.0,
            "train_initial_orientation_min": -180.0,
            "train_initial_orientation_max": 180.0,
            "orientation_change_probability": 3 / 50,
            "return_to_base_on_radius": 5.0,
            "return_to_base_off_radius": 2.0,
            "eval_initial_orientation": -180.0,
            "eval_left_x": -6.5,
            "eval_right_x": -3.5,
            "eval_left_orientation": 10.0,
            "eval_right_orientation": 170.0,
        },
        "command": {
            "type": "random",
            "sampling_type": "step_probability",
            "max_velocity_per_m_factor": 2.0,
            "clip_max_velocity": 1.0,
            "zero_clip_threshold_percentage": 0.1,
            "all_zero_chance": 0.04,
            "single_zero_chance": 0.005,
        },
        "gait_manager": {
            "type": "default",
            "gait_period": 1.0,
            "gait_period_randomization_width": 0.1,
        },
        "env_curriculum_nr_levels": 50,
        "env_curriculum_level_success_episode_return": 10.0,
        "domain_randomization": {
            "sampling_type": "step_probability_and_reset",
            "action_delay": {
                "type": "default",
                "max_nr_delay_steps": 1,
                "mixed_chance": 0.05,
            },
            "initial_state": {
                "type": "random",
                "roll_angle_pi_factor": 0.05,
                "pitch_angle_pi_factor": 0.05,
                "yaw_angle_pi_factor": 1.0,
                "actuator_joint_position_offset_to_nominal": 0.01,
                "actuator_joint_nominal_position_factor": 0.5,
                "joint_velocity_max_factor": 0.1,
                "trunk_velocity_clip_mass_factor": 0.1,
                "trunk_velocity_clip_limit": 0.5,
            },
            "joint_dropout": {
                "type": "default",
                "dropout_open_chance": 0.0,
                "dropout_lock_chance": 0.0,
            },
            "mujoco_model": {
                "type": "default",
                "friction_tangential_factor": 1.0,
                "friction_torsional_factor": 1.0,
                "friction_rolling_factor": 1.0,
                "stiffness_factor": 0.2,
                "damping_factor": 0.2,
                "foot_solimp_factor": 0.2,
                "add_impratio": 0.0,
                "xy_gravity": 0.0,
                "z_gravity_factor": 0.1,
                "density_factor": 0.1,
                "viscosity_factor": 0.1,
            },
            "observation_noise": {
                "type": "default",
                "joint_position": 0.01,
                "joint_velocity": 0.5,
                "imu_angular_velocity": 0.1,
                "gravity_vector": 0.02,
                "exteroception": 0.01,
                "ball_relative_position": 0.02,
            },
            "perturbation": {
                "sampling_type": "step_probability",
                "type": "default",
                "trunk_velocity_clip_mass_factor": 0.1,
                "trunk_velocity_clip_limit": 1.0,
                "trunk_velocity_add_chance": 0.5,
                "max_joint_velocity": 0.1,
                "max_joint_position": 0.01,
            },
            "seen_robot": {
                "type": "default",
                "robot_size_scaling_factor": 0.0,
                "coupled_mass_inertia_factor": 0.1,
                "decoupled_mass_inertia_factor": 0.05,
                "add_com_displacement": 0.005,
                "add_inertia_orientation_rad": 0.01,
                "add_body_position": 0.0,
                "add_body_orientation_rad": 0.0,
                "add_imu_position": 0.01,
                "foot_size_factor": 0.01,
                "joint_axis_angle_rad": 0.0,
                "torque_limit_factor": 0.05,
                "add_actuator_joint_nominal_position": 0.001,
                "joint_velocity_max_factor": 0.05,
                "add_joint_range": 0.01,
                "joint_damping_factor": 0.1,
                "add_joint_damping": 0.003,
                "joint_armature_factor": 0.1,
                "add_joint_armature": 0.001,
                "joint_stiffness_factor": 0.1,
                "add_joint_stiffness": 0.1,
                "joint_friction_loss_factor": 0.1,
                "add_joint_friction_loss": 0.00001,
                "p_gain_factor": 0.1,
                "d_gain_factor": 0.1,
                "scaling_factor_factor": 0.1,
            },
            "unseen_robot": {
                "type": "default",
                "mass_inertia_factor": 0.25,
                "com_factor": 0.1,
                "body_position_factor": 0.0,
                "joint_damping_factor": 0.0,
                "joint_armature_factor": 0.0,
                "joint_stiffness_factor": 0.0,
                "joint_friction_loss_factor": 0.0,
                "p_gain_factor": 0.2,
                "d_gain_factor": 0.2,
                "position_offset": 0.02,
            },
        },
        "policy_exteroceptive_observation_type": "none",
        "critic_exteroceptive_observation_type": "height_over_ground",
        "reward": {
            "type": "default",
            "tracking_xy_velocity_command_coeff": 0.0,
            "tracking_xy_temperature": 0.25,
            "tracking_yaw_velocity_command_coeff": 0.0,
            "tracking_yaw_temperature": 0.25,
            "alive_clipped_coeff": 0.05,
            "alive_unclipped_coeff": 0.05,
            "z_velocity_coeff": 2.0,
            "imu_acceleration_coeff": 1e-4,
            "roll_pitch_vel_coeff": 0.05,
            "roll_pitch_pos_coeff": 10.0,
            "actuator_joint_nominal_diff_coeff": 2.0,
            "joint_position_limit_coeff": 40.0,
            "soft_joint_position_limit": 0.9,
            "actuator_joint_velocity_limit_coeff": 5.0,
            "soft_actuator_joint_velocity_limit": 0.9,
            "joint_velocity_coeff": 4e-4,
            "joint_acceleration_coeff": 5e-6,
            "joint_torque_coeff": 4e-4,
            "power_draw_penalty_coeff": 4e-4,
            "action_rate_coeff": 10.0,
            "action_smoothness_coeff": 0.1,
            "collision_coeff": 2.0,
            "base_height_coeff": 120.0,
            "foot_air_time_coeff": 3.0,
            "foot_air_time_per_robot_size_m": 0.4,
            "symmetry_air_coeff": 1.0,
            "foot_slip_coeff": 0.1,
            "foot_z_velocity_coeff": 0.2,
            "feet_flat_coeff": 3.0,
            "feet_phase_coeff": 1.0,
            "feet_phase_swing_height": 0.12,
            "feet_phase_tracking_sigma": 0.1,
            "feet_height_on_flat_ground": 0.01,
            "feet_yaw_coeff": 5.0,
            "feet_lateral_distance_coeff": 0.5,
            "feet_lateral_distance_target_multiplier": 1.15,
            "feet_lateral_distance_ball_clearance": 0.08,
            "ball_velocity_tracking_coeff": 0.0,
            "ball_velocity_tracking_temperature": 0.25,
            "chasing_ball_coeff": 0.0,
            "yaw_to_ball_coeff": 1.0,
            "chasing_ball_temperature": 0.5,
            "com_chasing_ball_coeff": 16.0,
            "com_chasing_ball_exponent": 2.0,
            "close_ball_band_coeff": 0.0,
            "close_ball_band_target_distance": 0.35,
            "close_ball_band_temperature": 0.05,
            "yaw_alignment_coeff": 0.0,
            "active_sensing_coeff": 0.5,
            "residual_action_coeff": 0.0,
            "residual_action_smoothness_coeff": 0.0,
            "residual_action_head_l2_weight": 0.0,
            "residual_action_head_smoothness_weight": 0.1,
            "delta_command_coeff": 0.0,
            "delta_command_smoothness_coeff": 0.0,
            "fcp_dribble_coeff": 0.0,
            "fcp_dribble_lateral_coeff": 0.5,
            "fcp_dribble_forward_clip": 0.8,
            "fcp_dribble_gate_by_possession": False,
            "ball_possession_coeff": 0.0,
            "ball_possession_target_x": 0.25,
            "ball_possession_target_y": 0.0,
            "ball_possession_deadzone_x": 0.15,
            "ball_possession_deadzone_y": 0.16,
            "ball_possession_scale_x": 0.45,
            "ball_possession_scale_y": 0.30,
        },
        "termination": {
            "type": "below_height",
            "height_percentage_threshold": 0.8,
            "min_height_percentage_threshold": 0.75,
            "fall_height_percentage_threshold": 0.65,
            "enable_possession_termination": False,
            "enable_ball_stagnation_termination": False,
            "possession_warmup_steps": 50,
            "possession_min_x": -0.25,
            "possession_max_x": 0.75,
            "possession_max_abs_y": 0.45,
            "immediate_max_x": 1.20,
            "immediate_max_abs_y": 0.75,
            "ball_stagnation_warmup_seconds": 2.0,
            "ball_stagnation_max_seconds": 2.0,
            "ball_stagnation_min_displacement": 0.05,
            "ball_stagnation_command_speed_threshold": 0.15,
        },
        "terrain": {
            "type": "plane",
            "wave_fn_min": 0,
            "wave_fn_max": 2,
            "wave_height_max_per_m_factor": 0.3,
            "random_height_max_per_m_factor": 0.04,
            "block_probability": 0.5,
            "block_length_in_meters": 0.5,
            "block_height_max_per_m_factor": 0.1,
        },
        "add_goal_arrow": False,
        "timestep": 0.005,
        "episode_length_in_seconds": 20,
    }

    return config_dict.ConfigDict(config)
