# Time-Reversed Diffusion Sampler (DIS)
name: dis
underdamped: False
integrator: EM
init_std: 2.5
friction: 1.0

# diff_steps: 16
diff_steps: 8

use_target_score: ${hyperparameters.use_target_score}
learn_prior: False
learn_betas: False
learn_friction: True
learn_mass_matrix: False

defaults:
  - score_model: cond_pisgradnet
  - dt_schedule: cosine
