from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_mujoco.robocup_soccer.hierarchical_dribbling.mjx.create_env import create_train_and_eval_env
from rl_x.environments.custom_mujoco.robocup_soccer.hierarchical_dribbling.mjx.default_config import get_config
from rl_x.environments.custom_mujoco.robocup_soccer.hierarchical_dribbling.mjx.general_properties import GeneralProperties


ROBOCUP_SOCCER_HIERARCHICAL_DRIBBLING_MJX_ENV = extract_environment_name_from_file(__file__)
register_environment(ROBOCUP_SOCCER_HIERARCHICAL_DRIBBLING_MJX_ENV, get_config, create_train_and_eval_env, GeneralProperties)
