from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_mujoco.robocup_soccer.fcp_walk_policy_dribbling.mujoco.create_env import create_train_and_eval_env
from rl_x.environments.custom_mujoco.robocup_soccer.fcp_walk_policy_dribbling.mujoco.default_config import get_config
from rl_x.environments.custom_mujoco.robocup_soccer.fcp_walk_policy_dribbling.mujoco.general_properties import GeneralProperties


ROBOCUP_SOCCER_FCP_WALK_POLICY_DRIBBLING_MUJOCO_ENV = extract_environment_name_from_file(__file__)
register_environment(ROBOCUP_SOCCER_FCP_WALK_POLICY_DRIBBLING_MUJOCO_ENV, get_config, create_train_and_eval_env, GeneralProperties)