from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from rl_x.algorithms.reppo_pis.flax_full_jit.reppo_pis import RePPO_PIS
from rl_x.algorithms.reppo_pis.flax_full_jit.default_config import get_config
from rl_x.algorithms.reppo_pis.flax_full_jit.general_properties import GeneralProperties


REPPO_PIS_FLAX_FULL_JIT = extract_algorithm_name_from_file(__file__)
register_algorithm(REPPO_PIS_FLAX_FULL_JIT, get_config, RePPO_PIS, GeneralProperties)
